### PR TITLE
Add integration tests for the basic round trip

### LINKED ISSUE #169: Create integration tests for the Basic round trip
Need to figure out a way to test the basic round trip: https://github.com/alpine-hodler/gidari/blob/main/internal/web/auth/basic.go

### PR DESCRIPTION
**Pull request by axlts**
Resolves #169

### CODE REVIEW

**Comment by axlts** [comment]
@prestonvasquez can you review my PR?

**Comment by prestonvasquez** [comment]
@axlts There are a few linting errors. You can check these locally with `make lint` assuming you have the [golangci-lint](https://github.com/golangci/golangci-lint) binary installed. 

You will also need to run `make fmt` locally and push those updates.

**Comment by axlts** [comment]
@prestonvasquez Thanks a lot! I will fix the problems found by the linter and let you know. 

If you are satisfied with the tests written by me, can you assign me to the same issues (#167, #168 and #170)? I would like to work on these.

**Comment by prestonvasquez** [comment]
@axlts GitHub is kind of strange with assignments... since you aren't considered a "contributing member" yet, you need to comment on each of those tickets for me to assign you.

**Comment by prestonvasquez** [comment]
@axlts Outstanding work! Thank you so much for contributing this 💯

**Pull request merged**
